---
version: '3.8'

services:
  labstack:
    image: lscr.io/linuxserver/bookstack
    container_name: labstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=${LABSTACK_APP_URL}
      - DB_HOST=${LABSTACK_DB_HOST}
      - DB_PORT=${LABSTACK_DB_PORT}
      - DB_USER=${LABSTACK_DB_USER}
      - DB_PASS=${LABSTACK_DB_PASS}
      - DB_DATABASE=${LABSTACK_DB_DATABASE}
    volumes:
      - ./volumes/app-data:/config
    ports:
      - "${LABSTACK_UI_PORT}:80"
    restart: unless-stopped
    depends_on:
      - labstack_db

  labstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: labstack_db
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${LABSTACK_DB_ROOT_PASS}
      - TZ=${LABSTACK_TZ}
      - MYSQL_DATABASE=${LABSTACK_DB_DATABASE}
      - MYSQL_USER=${LABSTACK_DB_USER}
      - MYSQL_PASSWORD=${LABSTACK_DB_PASS}
    volumes:
      - ./volumes/db-data:/config
    restart: unless-stopped

networks:
  default:
    external: true
    name: dockerbox