---
version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss:10.2.3
    container_name: grafana
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes:
      - ./volumes/grafana-data:/var/lib/grafana

networks:
  default:
    external: true
    name: dockerbox