---
version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - ${PORTAINER_UI_PORT}:9443
    volumes:
        - ./volumes/data:/data
        - /var/run/docker.sock:/var/run/docker.sock