---
version: '3.8'

services:
  influxdb:
    image: influxdb:2.7.4
    container_name: influxdb
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - '${INFLUXDB_PORT}:8086'
    volumes:
      - ./volumes/influxdb-data:/var/lib/influxdb2
      - ./volumes/influxdb-config:/etc/influxdb2

networks:
  default:
    external: true
    name: dockerbox