---
version: '3.8'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - '${KUMA_HTTP_PORT}:80'
      - '${KUMA_HTTPS_PORT}:443'
      - '${KUMA_ADMIN_PORT}:81'
    volumes:
      - ./volumes/data:/data
      - ./volumes/letsencrypt:/etc/letsencrypt

networks:
  default:
    external: true
    name: dockerbox